rootProject.name = "samples"

include(":trivia:trivia-host")
include(":trivia:trivia-js")
include(":trivia:trivia-shared")
include(":world-clock:android")
include(":world-clock:ios:shared")
include(":world-clock:presenters")

dependencyResolutionManagement {
  versionCatalogs {
    libs {
      from(files("../gradle/libs.versions.toml"))
    }
  }
}

includeBuild('..') {
  dependencySubstitution {
    substitute module("io.github.tret9:zipline") using project(":zipline")
    substitute module("io.github.tret9:zipline-cli") using project(":zipline-cli")
    substitute module("io.github.tret9:zipline-gradle-plugin") using project(":zipline-gradle-plugin")
    substitute module("io.github.tret9:zipline-kotlin-plugin") using project(":zipline-kotlin-plugin")
    substitute module("io.github.tret9:zipline-loader") using project(":zipline-loader")
    substitute module("io.github.tret9:zipline-profiler") using project(":zipline-profiler")
  }
}
