object Dependencies {
  val androidGradlePlugin = "com.android.tools.build:gradle:7.0.2"
  val androidMaterial = "com.google.android.material:material:1.4.0"
  val androidxActivityCompose = "androidx.activity:activity-compose:1.4.0-alpha01"
  val androidxAnnotation = "androidx.annotation:annotation:1.1.0"
  val androidxAppCompat = "androidx.appcompat:appcompat:1.3.1"
  val androidxCoreKtx = "androidx.core:core-ktx:1.6.0"
  val androidxLifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1"
  val androidxTestRunner = "androidx.test:runner:1.2.0"
  val coilCompose = "io.coil-kt:coil-compose:1.3.2"
  val composeMaterial = "androidx.compose.material:material:1.1.0-rc01"
  val composeUi = "androidx.compose.ui:ui:1.1.0-rc01"
  val composeUiTooling = "androidx.compose.ui:ui-tooling:1.1.0-rc01"
  val composeUiToolingPreview = "androidx.compose.ui:ui-tooling-preview:1.1.0-rc01"
  val dokkaGradlePlugin = "org.jetbrains.dokka:dokka-gradle-plugin:1.6.10"
  val desugarJdkLibs = "com.android.tools:desugar_jdk_libs:1.1.5"
  val cklibGradlePlugin = "co.touchlab:cklib-gradle-plugin:0.2.4"
  val duktape = "com.squareup.duktape:duktape-android:1.4.0"
  val graalvm = "22.0.0.2"
  val graalGradlePlugin = "gradle.plugin.com.palantir.graal:gradle-graal:0.10.0"
  val junit = "junit:junit:4.13.2"
  val mavenPublishGradlePlugin = "com.vanniktech:gradle-maven-publish-plugin:0.18.0"
  val picocli = "info.picocli:picocli:4.6.3"
  val picocliCompiler = "info.picocli:picocli-codegen:4.6.3"
  val shadowJarPlugin = "gradle.plugin.com.github.johnrengelman:shadow:7.1.2"
  val sqldelightJdbc = "org.xerial:sqlite-jdbc:3.34.0"
}
