#!/bin/bash -e

../gradlew -q --console plain shadowJar

VERSION=$(cut -d = -f 2 < ./build/generated/resources-templates/zipline-cli-version.properties)
JAR_PATH="./build/libs/zipline-cli-${VERSION}-all.jar"

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  java -jar $JAR_PATH
elif [[ "$OSTYPE" == "darwin"* ]]; then
  java -jar $JAR_PATH
elif [[ "$OSTYPE" == "cygwin" ]]; then
  java.exe -jar $JAR_PATH
elif [[ "$OSTYPE" == "msys" ]]; then
  java.exe -jar $JAR_PATH
elif [[ "$OSTYPE" == "win32" ]]; then
  java.exe -jar $JAR_PATH
elif [[ "$OSTYPE" == "freebsd"* ]]; then
  java -jar $JAR_PATH
else
  echo "Unknown platform ""$OSTYPE"". Run \$ java -jar $JAR_PATH"
fi
